Portfolio
toyman640/Portfolio-setup pull request #1
Opened 2023-02-18 06:37 UTC by toyman640

i implement a first version of my portfolio

2023-02-18 06:47 UTC, Kamba56 requested changes
Hi @toyman640, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 06:47 UTC, Kamba56 commented on index.html
> +                </div>
- [Optional] There seems to be too much margin on the side of your headline section and it is pushing everything out of the screen to the right. Consider fixing this, please.

2023-02-18 06:47 UTC, Kamba56 commented on index.html
> +        </section>
- [ ] Kindly add the work section and the about me section, these are the core of this milestone.
### WOrk section
![f1](https://user-images.githubusercontent.com/94551484/219845815-49c0615f-0bc8-41d4-976b-430dee73df74.png)

### about section
<img width="188" alt="f2" src="https://user-images.githubusercontent.com/94551484/219845820-c20e9629-d413-4e0d-b469-6ed7986c4706.png">

2023-02-18 06:47 UTC, Kamba56 commented on index.html
> +                <img class="elli-2" src="images/Ellipse 5.svg" alt="" srcset="">
- [ ] Please use an indentation of two spaces in all your documents. THis is a best practice and also a convention.

2023-02-18 14:33 UTC, Favourezeugwa requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @toyman640 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![close lady](https://user-images.githubusercontent.com/99246359/207367678-ef4e9b86-75b7-4d8e-b9b5-899f2e87c934.gif)

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 14:33 UTC, Favourezeugwa commented on index.html
> +                </div>
- I'd like to kindly suggest that you group your icons in a `ul` tag and each icon in an `li` . Also, each icon has a link (a tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. 🌸 

Something like this will be fine 👇🏽 
```
<ul class="icons">
     <li><a href = "yourtwitterhandle.com><img  class="twitter" src="images/twitter.svg" alt="" srcset=""></a></li>
      .......
</ul>
```

2023-02-18 14:33 UTC, Favourezeugwa commented on style.css
> +}
- I think it will be better if you added some margins to the right side of your mobile portfolio. The `margin-left: 80px;` can be replaced with `margin: 0 30px;` so that it applies on both sizes. You are free to modify the `px` as you wish, just make sure everything is uniform. 🌸 

This is what I could see compared to figma 👇🏽 

| Your Design  | Figma Design |
| :---:   | :---: | 
| <img width="380" alt="Screenshot 2023-02-18 at 08 24 14" src="https://user-images.githubusercontent.com/99246359/219871307-9f1662d7-97e2-4239-ac6b-61dd5bc98311.png"> |<img width="300" alt="Screenshot 2023-02-18 at 08 31 08" src="https://user-images.githubusercontent.com/99246359/219871366-6df54c0e-543c-4568-80c9-d614b024d065.png">  |

2023-02-20 09:28 UTC, Ibizugbe requested changes
Hi @toyman640 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/220066110-60f77e4e-f553-4ae3-aba5-4bfc264ab1a9.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [ ] Linters are passing👍
- [ ] Github flow has been used👍👍


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 09:28 UTC, Ibizugbe commented on index.html
> +                <img class="elli-3" src="images/Ellipse 3 (1).svg" alt="" srcset="">
If you're using an image tag to display your background image, I suggest you add an `alt` attribute for semantic reasons😉
kindly do that for all your images😉

2023-02-20 09:28 UTC, Ibizugbe commented on index.html
> +          <img class="nav-ham" src="images/icons8-menu-24.png" alt="ham" srcset="">
Nice work on your toolbar👍 but we can make some improvements so we stick to the design😉
- Kindly take note of your hamburger bar, it looks different from the design😎

design
![toolbar-mobile (1)](https://user-images.githubusercontent.com/64643995/220064090-7e5c1801-e1db-43e7-83f2-f4f6a2e45713.png)

yours
<img width="284" alt="your_hamb" src="https://user-images.githubusercontent.com/64643995/220064127-52de9b5e-4cd5-45f8-85fd-5ad3f78c2bb0.png">

also take not of the position of the bar (the space around it)😉

2023-02-20 09:28 UTC, Ibizugbe commented on index.html
> +                        <li><a href="http://"><img class="angellist" src="images/angellist.svg" alt="" srcset=""> </a></li>
Your content section is looking a bit different from the design😉 lets improve it by taking note of the spacing and font properties😊

<img width="282" alt="your page" src="https://user-images.githubusercontent.com/64643995/220065071-036fceaf-ac7f-439d-a1d8-b84ae4231633.png">

design
![headline-mobile](https://user-images.githubusercontent.com/64643995/220065159-132af24c-f38b-4438-b9a8-d602a844d6c7.png)

Also, take note of the position of the background image😉 I can see you used absolute positioning to place them which is very fine, This is optional but I think you can also download the entire background image in the design and use the css `background` properties to position it😉 

but in all, kindly ensure the background image is well positioned😎

2023-02-20 12:56 UTC, topeogunleye requested changes
Hi @toyman640, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Please kindly check the inline comments

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 12:56 UTC, topeogunleye commented on index.html
> +                <img class="rec-1" src="images/Rectangle 6.svg" alt="" srcset="">
- [ ] As suggested by the previous reviewer, I kindly suggest that you add a description of your image through you alt html attribute. Please do not leave them empty.
- [ ] [OPTIONAL] It is a requirement to use `background-image` property for these images because they are for aesthetic reasons and not a part of the content.

2023-02-20 12:56 UTC, topeogunleye commented on index.html
> +                <p class="socials-header">LET’S CONNECT</p>
- [ ][OPTIONAL] I kindly suggest that you ensure that the spacing between the icons is the same as the Figma design

| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="274" alt="image" src="https://user-images.githubusercontent.com/52934128/220113643-7b17ea67-1593-4794-8cbe-f8f5890e19a3.png"> | <img width="374" alt="image" src="https://user-images.githubusercontent.com/52934128/220113915-88fd5785-a27d-47d4-bb9b-addb303a7d11.png"> |

2023-02-20 13:42 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 14:42 UTC, topeogunleye reviewed
Hi @toyman640, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses an old PR for a new Milestone Review Request. Be informed that you need to create a new pull request for every new Milestone

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-21 15:04 UTC, merged